name: fjc-mvc
services:
  db:
    image: "postgres:17.2-bookworm"
    container_name: fjc-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fjc_develop
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: fjc
      DATABASE_PASSWORD: password
    volumes:
      - data:/var/lib/postgresql@15/data
volumes:
  data:
