default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: fjc_test

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: fjc_develop

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: fjc_prod
